---
tags: Java/Исключения
---
## Оператор `throw`

Исключение, пока оно не выброшено в систему, или когда оно уже перехвачено блоком `catch` — это в принципе просто объект класса, унаследованного от `Exception` (вернее, от `Throwable`). Никакими магическими особенностями сам объект-исключение не обладает.

Вся логика работы исключений — это просто особый сценарий поведения Java-машины, когда в ее среду выполнения вброшено исключение.

Оператор `throw` используется для генерирования исключений в программе. Мы можем использовать оператор `throw`, чтобы выбросить исключение при возникновении определенных условий.

Когда в программе возникает исключительная ситуация, программист может использовать оператор `throw` для явного выброса (генерации) исключения. Синтаксис оператора `throw` выглядит следующим образом:
```java
throw исключение;
```

Здесь `исключение` представляет собой объект-исключение или экземпляр класса исключения, который требуется сгенерировать.

Пример:
```java
public void divide(int dividend, int divisor) {
	if (divisor == 0) {
		throw new ArithmeticException("Деление на ноль недопустимо");
	}        
	int result = dividend / divisor;
	System.out.println("Результат: " + result);    
}
```

В приведенном примере, если значение `divisor` равно нулю, то будет сгенерировано исключение `ArithmeticException` с сообщением «Деление на ноль недопустимо».
## Ключевое слово `finally`

Блок `finally` опционален и следует после блока `catch`. Он содержит код, который будет выполнен независимо от того, произошло исключение или нет. Блок `finally` используется, например, для закрытия открытых ресурсов или выполнения завершающих операций.
```java
try
{
   код, где может возникнуть ошибка
}
catch(ТипИсключения имя)
{
   код обработки исключения
}
finally
{
   код, который нужно выполнить в любом случае
}
```

Для выполнения таких обязательных действий к оператору `try-catch` добавили еще один блок — `finally`, и получился оператор `try-catch-finally`.

**Finaly** отработает даже если:
- в **try** будут **break**
- в **try** будут **return**
- исключение из **try** обработано блоком **catch**
- исключение из **try** не поймано ни одним блоком **catch**
- блоком **catch** выброшено новое исключение
finally не выполнится с System.exit(0) или если во время try виртуальная машина легла.
![[Особые случаи когда finally не выполняется.png]]

> [!NOTE]
Если в **finaly** и в **try** вылетело исключение, то исходное исключение из **try** будет потеряно. Поэтому можно встретить блок **try - catch** внутри блока **finally**


> [!NOTE]
> **Try** требует наличие либо **catch**, либо **finally**